default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: shipment_tracker
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shipment_tracker_development

test:
  <<: *default
  database: shipment_tracker_test
  pool: 5

production:
  <<: *default
  database: shipment_tracker_production
  pool: 20
